# Generated by Django 5.0.1 on 2024-02-19 11:05

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_videocomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocategory',
            options={'verbose_name_plural': 'Video Categories'},
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(null=True, upload_to='video_uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['webm', 'mkv', 'flv', 'vob', 'ogv', 'ogg', 'rrc', 'gifv', 'mng', 'mov', 'avi', 'qt', 'wmv', 'yuv', 'rm', 'asf', 'amv', 'mp4', 'm4p', 'm4v', 'mpg', 'mp2', 'mpeg', 'mpe', 'mpv', 'm4v', 'svi', '3gp', '3g2', 'mxf']), base.models.validate_file_mimetype]),
        ),
    ]
